version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: backend-louve
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '6WRJ7nZLDrEO0dD9Cj2v'
      MYSQL_DATABASE: 'railway'
    ports:
      - '3306:6363'